-- Re-sync all "GENERATED BY DEFAULT AS IDENTITY" sequences to MAX(id) of each table.
--
-- Why this is needed:
--   The schema uses `IdentityByDefaultColumn` (GENERATED BY DEFAULT AS IDENTITY).
--   When rows are inserted with explicit id values (manual SQL import / DB restore /
--   seed script), PostgreSQL does NOT advance the underlying identity sequence.
--   The next auto-generated id then collides with an existing row, producing:
--     23505: duplicate key value violates unique constraint "pk_users"
--
-- This script walks every identity column in the database and calls setval() so the
-- sequence resumes just above the current MAX(id). It is safe and idempotent -- run
-- it whenever you import/restore data with explicit ids.

DO $$
DECLARE
    rec        RECORD;
    seq_name   TEXT;
    max_id     BIGINT;
BEGIN
    FOR rec IN
        SELECT c.table_schema, c.table_name, c.column_name
        FROM   information_schema.columns c
        WHERE  c.is_identity = 'YES'
    LOOP
        seq_name := pg_get_serial_sequence(
                        format('%I.%I', rec.table_schema, rec.table_name),
                        rec.column_name);

        IF seq_name IS NULL THEN
            CONTINUE;
        END IF;

        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I.%I',
                       rec.column_name, rec.table_schema, rec.table_name)
        INTO max_id;

        -- is_called = (max_id > 0): if the table has rows, next value is max_id + 1;
        -- if empty, the sequence starts fresh at 1.
        PERFORM setval(seq_name, GREATEST(max_id, 1), max_id > 0);

        RAISE NOTICE 'Re-synced %.% (%) -> next id after %',
                     rec.table_schema, rec.table_name, seq_name, max_id;
    END LOOP;
END $$;
