<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ApartmentManagementSystem.Domain</AssemblyName>
    <RootNamespace>ApartmentManagementSystem.Domain</RootNamespace>
  </PropertyGroup>

</Project>
